### ISSUE TITLE
Display flex makes child elements fill the col width

### ISSUE THREAD

**Issue by dg-teamweb** [vivid-web/flexbox-grid-sass#13]
Hi!

We've been using your library for a while now and i think its awesome! 

Today we've tried to update to the new repository and the latest 5.0.3 version but found a "bug (?)"
When you add the default .col and for example .col--sm classes all childs inside that col are stretched to the full width of the column. This happens because the default col class also has a display: flex now.

There's also a variant ```.col--flex``` which also adds display: flex; which makes the initial ```display: flex;``` unnecessary right?

Is there way to prevent the streching in the current version?

**Comment by dg-teamweb** [comment]
Demo of thie issue: https://codepen.io/anon/pen/ZjNvza

**Comment by petervmeijgaard** [comment]
Hi @dg-teamweb,

You are correct! I've removed the `display: flex` rule in the latest version. Please upgrade to version `5.0.4` and it will work just fine :)

Thanks for improving the quality of this project!
