### ISSUE TITLE
Download buttons on the documentation page downloads the wrong version

### ISSUE THREAD

**Issue by dg-teamweb** [vivid-web/flexbox-grid-sass#14]
The minified version you can download on the documentation site isn't the latest verison on Github. I think it's still the 4.* version.

**Comment by petervmeijgaard** [comment]
Hi @dg-teamweb,

The version that's being downloaded is the Stylus version, which is the correct one. The SASS version that you are referring to has the bug where a column is set to `display: flex`. This bug is fixed in the latest version of this package.
