### ISSUE TITLE
Documentation / site are unavaliable

### ISSUE THREAD

**Issue by ivangretsky** [vivid-web/flexbox-grid-sass#4]
Good day!
The links are broken. Is it discontinued?

**Comment by petervmeijgaard** [comment]
The links are indeed broken. I switched from hosting provider and I forgot to re-upload the site. I can't do it right now, because I'm on vacation and I don't have a laptop with me. I'll be back in a few days.

**Comment by petervmeijgaard** [comment]
The website flexboxgrid.vivid-websolutions.nl is working again! 😄

**Comment by ivangretsky** [comment]
Cool!
It seems like there is some problems with SSL certificate - can't open the site in Firefox (works fine in Chrome though). Please check it when you got time.

**Comment by petervmeijgaard** [comment]
Thanks for the headsup! There was indeed a problem with the SSL certificate. I believe it's fixed now 😄
