### ISSUE TITLE
Make row and col elements of container?

### ISSUE THREAD

**Issue by ivangretsky** [vivid-web/flexbox-grid-sass#5]
Good day!

Bootstrap grid classes are supposed to be used a s a system (I mean as a block in BEM). That means we can't use `row` outside of `container` and `col` outside of `row`. It seems logical to rename those classes according to BEM methodology  the following way:

- `.layout` or `.grid` instead of `.container`
- `.layout__row` or `.grid__row` instead of `.row`
- `.layout__col` or `.grid__col` instead of `.col`

What do you think?

**Comment by petervmeijgaard** [comment]
Hi @ivangretsky!

Thanks for the feedback and giving me something to chew on. In the first version of the grid, I considered this as well, but that made things a bit too complicated for me. I agree that a row cannot live outside a grid, but neither can a col live outside a row.
So this will lead to the following classes, which makes it kinda weird:
 - `.grid`
 - `.grid__row`
 - `.grid__row__col`
 - `.text`

To be honest, I'm not really sure if a element can have another element as a child/parent relationship. What are your thought about this?

My apologies for the late response. Updating the repository has been on my todo list for a long time, but I couldn't find the time to do this. I've already updated the grid drastically and it is easier for me to add functionality in the future. Thanks for thinking with me and making the grid better each step.

**Comment by ivangretsky** [comment]
According to BEM principles there [should not be an elements of an element](http://getbem.com/faq/#css-nested-elements). But frankly speaking I am now just using Bootstrap grid "as is" (only including [bootstrap-grid.scss](https://github.com/twbs/bootstrap/blob/v4-dev/scss/bootstrap-grid.scss)), as it is easier to teach and to support. All the other components are named in BEM convention though.

But something like this library IMHO should go BEM-style all the way, like [inuit](https://github.com/inuitcss/inuitcss/blob/develop/objects/_objects.layout.scss) or [Blaze](https://www.blazeui.com/objects/grid).

Thanks for your work!
