### ISSUE TITLE
Enhancement: Padding as variable

### ISSUE THREAD

**Issue by MarcelHekkert** [vivid-web/flexbox-grid-sass#6]
I've noticed padding default is defined within .row while it would be more flexible to set it as a variable. Just a thought.

Other than that the grid is really full featured and nicely documented.

**Comment by petervmeijgaard** [comment]
Hi @MarcelHekkert!

Sounds like a good feature! Keep in mind that the sizing for the whole grid is defined in REM-units. So you can simply change the font-size to a bigger font set the padding as well. Unfortunately does this also impact the overall sizing of the website.
Do you mean that you want a different sizing for the gutter and the padding or one variable to rule them all?

My apologies for the late response. Updating the repository has been on my todo list for a long time, but I couldn't find the time to do this. I've already updated the grid drastically and it is easier for me to add functionality in the future. I'll have a solution to your issue at the end of the week ready and implemented.
If you have any questions, feel free to ask them and I'll answer the shortly.

**Comment by petervmeijgaard** [comment]
It hink this issue is fixed in https://github.com/vivid-web/flexboxgrid-sass/commit/6acc05edec230842cbb45f0e1301fc472c82d3d5 and released in V5.0.2.

I'll close this issue for now, but feel free to reopen it if your problem isn't fixed.
